ansible_connection: ssh
ansible_user: root
ansible_ssh_private_key_file: ~/.ssh/id_rsa

gather_facts: True
gathering: smart


host_key_checking: False


install_temp_dir: /tmp/ansible-install
install_dir: /mnt/data0/spark
spark_history_dir: /tmp/spark-events


